Repository jupyterhub/jupyter-remote-desktop-proxy, pull requests merged in 2023-06, with the labels that each got.

#34 Remove hardcoded display number and port, avoids multi-user conflicts
  jupyter_remote_desktop_proxy/__init__.py
Labels: bug

#39 ci: fix typo in manics/action-binderbadge version
  .github/workflows/binder-badge.yaml
Labels: ci

#40 Add PyPI/Issues/Forum badges for readme
  README.md
Labels: documentation

#37 Backfill changelog for 1.0.0 and 0.1.3
  CHANGELOG.md
Labels: documentation

#38 Add RELEASE.md, adopt tbump, rename release workflow for consistency
  .github/workflows/release.yaml
  RELEASE.md
  pyproject.toml
Labels: maintenance
