Repository jupyterhub/jupyter-remote-desktop-proxy, pull requests merged in 2023-01, with the labels that each got.

#21 Add installation instructions
  README.md
Labels: documentation

#23 ci: update outdated github actions
  .github/workflows/binder-badge.yaml
  .github/workflows/publish.yml
Labels: ci

#22 maint: add dependabot for github actions
  .github/dependabot.yaml
Labels: maintenance

#13 Remove apt.txt and refactor Dockerfile
  Dockerfile
  apt.txt
  environment.yml
  setup.py
Labels: maintenance

#25 maint: add pre-commit config
  .flake8
  .pre-commit-config.yaml
  LICENSE
  MANIFEST.in
  README.md
  jupyter_remote_desktop_proxy/__init__.py
  pyproject.toml
  setup.py
Labels: maintenance
