Repository jupyterhub/jupyter-remote-desktop-proxy, pull requests merged in 2024-02, with the labels that each got.

#86 [Docker image] Install fonts-dejavu for use by terminals
  Dockerfile
Labels: bug

#90 Require python 3.8+, up from 3.6+
  pyproject.toml
  setup.py
Labels: maintenance, breaking

#94 Publish TigerVNC and TurboVNC image to quay.io
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Dockerfile
Labels: new

#95 Fix automation to publish tigervnc and turbovnc images
  .github/workflows/release.yaml
Labels: maintenance

#91 Require jupyter-server-proxy 4+
  setup.py
Labels: maintenance, breaking
