Repository jupyterhub/jupyter-remote-desktop-proxy, pull requests merged in 2025-03, with the labels that each got.

#142 Pin js dependency novnc to 1.5.0 until we support 1.6.0
  package.json
Labels: maintenance

#134 Override xstartup with environment variable `JUPYTER_REMOTE_DESKTOP_PROXY_XSTARTUP`
  README.md
  jupyter_remote_desktop_proxy/setup_websockify.py
Labels: new

#147 Build and package JS built with webpack --mode production
  package.json
  webpack.config.js
Labels: bug

#145 Access TurboVNC via a unix socket instead of a port
  .github/workflows/test.yaml
  README.md
  jupyter_remote_desktop_proxy/setup_websockify.py
Labels: enhancement, breaking

#148 Add changelog for v3.0.0
  CHANGELOG.md
Labels: documentation
